---
- name: Check if node already joined
  command: test -f /etc/kubernetes/kubelet.conf
  register: kubelet_conf
  failed_when: false
  changed_when: false

- name: Join node to cluster
  command: "{{ hostvars[groups['control_plane'][0]].kubeadm_join_command }} --ignore-preflight-errors=all"
  when: kubelet_conf.rc != 0